# Generated by Django 4.0.2 on 2022-12-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(default='EUR', max_length=4),
        ),
    ]
