# Generated by Django 4.2.1 on 2024-04-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0003_account_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
