# Generated by Django 4.0.2 on 2023-04-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Templates",
            "0002_alter_template_account_alter_template_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="type",
            field=models.SmallIntegerField(
                choices=[(0, "Income"), (1, "Expense"), (2, "Transfer")],
                default=(0, "Income"),
            ),
        ),
    ]
