# Generated by Django 4.0.2 on 2023-04-17 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Templates', '0007_rename_templategroup_template_template_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='date',
        ),
    ]
