# Generated by Django 4.2.1 on 2024-02-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_initial"),
        ("Templates", "0008_remove_template_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="tags",
            field=models.ManyToManyField(to="tags.tag"),
        ),
    ]
