trigger:
  - master

pool:
  name: server1_pool

variables:
  dockerComposeFile: "docker-compose.yml"

stages:
  - stage: BuildAndDeploy
    displayName: "Build and Deploy BudgetManager"
    jobs:
      - job: StopContainers
        displayName: "Stop Existing Containers (frontend & backend)"
        steps:
          - script: |
              echo "Stopping containers..."
              docker stop budgetmanager_backend budgetmanager_frontend || true
              docker rm -f budgetmanager_backend budgetmanager_frontend || true
              docker network rm budgetmanager_budget_network || true
            displayName: "Remove Containers And Network"
            continueOnError: false

      - job: StartContainers
        displayName: "Start New Containers (frontend & backend)"
        dependsOn: StopContainers
        condition: succeeded('StopContainers')
        steps:
          - script: |
              echo "Building and starting new containers..."
              docker-compose -f $(dockerComposeFile) -p budgetmanager up -d --build
            displayName: "Run docker-compose up"

  - stage: Cleanup
    jobs:
      - job: CleanupResources
        steps:
          - bash: |
              echo "Cleaning build directory"
              rm -rf $(Agent.BuildDirectory)/*

              echo "Cleaning docker resources (unused images and volumes)"
              docker image prune -af
              docker volume prune -f
        displayName: "Clean up pipeline resources"
