# Generated by Django 4.0.2 on 2022-11-30 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DimIncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FactTranscation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField(default=0.0)),
                ('type', models.IntegerField(choices=[(0, 'Income'), (1, 'Expense'), (2, 'Transfer')])),
                ('transfer_reason', models.CharField(default='', max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='Accounts.dimaccount')),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_category', to='Transactions.dimexpensecategory')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='Accounts.dimaccount')),
                ('income_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_category', to='Transactions.dimincomecategory')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='Accounts.dimaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
