# Generated by Django 4.0.2 on 2022-11-30 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '__first__'),
        ('Transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facttranscation',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='Accounts.dimaccount'),
        ),
        migrations.AlterField(
            model_name='facttranscation',
            name='expense_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='expense_category', to='Transactions.dimexpensecategory'),
        ),
        migrations.AlterField(
            model_name='facttranscation',
            name='from_account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='Accounts.dimaccount'),
        ),
        migrations.AlterField(
            model_name='facttranscation',
            name='income_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='income_category', to='Transactions.dimincomecategory'),
        ),
        migrations.AlterField(
            model_name='facttranscation',
            name='to_account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='Accounts.dimaccount'),
        ),
        migrations.AlterField(
            model_name='facttranscation',
            name='transfer_reason',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
