# Generated by Django 4.2.1 on 2024-02-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_initial"),
        ("Transactions", "0003_expense_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="tags",
            field=models.ManyToManyField(to="tags.tag"),
        ),
        migrations.AddField(
            model_name="transfer",
            name="tags",
            field=models.ManyToManyField(to="tags.tag"),
        ),
    ]
