# Generated by Django 4.0.2 on 2022-11-30 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0003_alter_facttranscation_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facttranscation',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
