# Generated by Django 4.0.2 on 2022-12-01 20:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '__first__'),
        ('Transactions', '0004_facttranscation_created_on'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FactTranscation',
            new_name='FactTransaction',
        ),
    ]
