# Generated by Django 4.2.1 on 2024-02-26 13:24

from django.db import migrations, models
import django.db.models.deletion

from Transactions.models import TransactionCategory


def up(self, schema_editor):
    from Transactions.models import TransactionCategory, Income, Expense

    # Loop through all income records
    # Loop through all income records
    for income in Income.objects.all():
        old_category_id = income.income_category_id

        # Check if the category exists in the new table
        if TransactionCategory.objects.filter(pk=old_category_id).exists():
            new_category = TransactionCategory.objects.get(pk=old_category_id)
            income.income_category = new_category
            income.save()
        else:
            # Handle cases where the category doesn't exist
            # (log, ignore, etc. based on your needs)
            print(
                f"income record with id {income.id} references non-existent category id {old_category_id}"
            )

    # Loop through all income records
    for expense in Expense.objects.all():
        old_category_id = expense.expense_category_id

        # Check if the category exists in the new table
        if TransactionCategory.objects.filter(
            pk=old_category_id + 10
        ).exists():
            new_category = TransactionCategory.objects.get(
                pk=old_category_id + 10
            )
            expense.expense_category = new_category
            expense.save()
        else:
            # Handle cases where the category doesn't exist
            # (log, ignore, etc. based on your needs)
            print(
                f"expense record with id {expense.id} references non-existent category id {old_category_id}"
            )


class Migration(migrations.Migration):
    dependencies = [
        ("Transactions", "0004_income_tags_transfer_tags"),
    ]

    operations = [migrations.RunPython(up)]
