# Generated by Django 4.2.1 on 2026-06-05 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tags", "0002_tag_created_on"),
        ("Transactions", "0008_delete_smoke_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="income",
            name="account",
        ),
        migrations.RemoveField(
            model_name="income",
            name="income_category",
        ),
        migrations.RemoveField(
            model_name="income",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="income",
            name="user",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="from_account",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="to_account",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="user",
        ),
        migrations.AddField(
            model_name="transaction",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="tags",
            field=models.ManyToManyField(blank=True, to="tags.tag"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transactioncategory",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="transactioncategory",
            name="category_type",
            field=models.IntegerField(choices=[(0, "income"), (1, "expense")]),
        ),
        migrations.DeleteModel(
            name="Expense",
        ),
        migrations.DeleteModel(
            name="Income",
        ),
        migrations.DeleteModel(
            name="Transfer",
        ),
    ]
