# Generated by Django 4.2.1 on 2026-06-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Transactions",
            "0009_remove_income_account_remove_income_income_category_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="applied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="draft_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="scheduled_apply_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "is_draft", "date"], name="txn_user_draft_date_idx"
            ),
        ),
    ]
