# Generated by Django 4.2.1 on 2026-06-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Transactions",
            "0010_transaction_applied_at_transaction_draft_created_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="draft_created",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
