# Generated by Django 4.2.1 on 2026-08-08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "Transactions",
            "0011_alter_transaction_draft_created",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="scheduled_apply_at",
        ),
    ]
