# Generated by Django 4.2.1 on 2026-05-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("base_currency", models.CharField(default="USD", max_length=3)),
                ("quote_currency", models.CharField(max_length=3)),
                ("rate", models.DecimalField(decimal_places=10, max_digits=20)),
                ("provider", models.CharField(default="frankfurter", max_length=50)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["date", "base_currency", "quote_currency"],
                        name="fx_rate_lookup_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="exchangerate",
            constraint=models.UniqueConstraint(
                fields=("date", "base_currency", "quote_currency", "provider"),
                name="unique_exchange_rate_per_day_provider",
            ),
        ),
    ]
